include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    always_use_package_imports: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: false
